galaxy_info:
  author: Calidae
  description: Set hostname
  company: Calidae S.L.
  license: MIT
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - bionic
  galaxy_tags:
    - common
dependencies: []
