- name: apt install rsyslog
  apt:
    name: rsyslog
    update_cache: yes

- name: logs directory
  file:
    path: '{{ logs_folder }}'
    owner: syslog
    group: '{{ system_user.name }}'
    mode: 0775
    state: directory

- name: set rsyslog {{ type }} config file
  template:
    src: rsyslog.j2
    dest: /etc/rsyslog.d/10-{{ type }}.conf
    owner: root
    group: root
    mode: 0644
  notify: restart rsyslog